name: Build Next.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Generate GraphQL types
        run: yarn generate

      - name: Build Next.js app
        env:
          WORDPRESS_API_URL: ${{ secrets.WORDPRESS_API_URL }}
        run: yarn build
